### ISSUE TITLE
请问支持正则匹配允许玩家自行添加模组吗？

### ISSUE THREAD

**Issue by joe-vettek** [z2bguoguo/zdgxmc#2]
如题所示，有些客户端模组并不是所有人都需要，但是wiki好像没看到可以允许玩家自行加模组的方法

**Comment by z2bguoguo** [comment]
这个你是需要按wiki里提供的方法制作个读取的链接，本mod会通过链接进行更新，在wiki中“更新数据获取的链接”就是配置mod内容的链接，通过更改链接内部的内容来实现需要哪些mod
你可以在仔细阅读一下wiki[https://github.com/z2bguoguo/zdgxmc/wiki/Zdgx-Mod-%E6%95%99%E7%A8%8B#%E7%9B%AE%E5%BD%95](url)
这是示例链接：“https://raw.githubusercontent.com/z2bguoguo/mczdgx/main/json.json”
如果还不会可以参考我的教程视频：youtube：[https://youtu.be/wNNw7qTQd7g](url)
哔哩哔哩：[https://www.bilibili.com/video/BV13Y4y1u7aK/](url)

**Comment by joe-vettek** [comment]
好的谢谢
